#!/usr/bin/env php
<?php

require __DIR__."/vendor/autoload.php";

$instance = require_once __DIR__."/bootstrap/app.php";

$output = ($instance)->handleCommand($input = new \Symfony\Component\Console\Input\ArgvInput);

exit($output);
